encoding: utf-8

#url: http://ioioj5.github.io
url: http://www.woniu.me
name: __都非拉得的博客

# markdown: kramdown

# code highlighting
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# standard jekyll configuration options
exclude: ['Rakefile', 'README.md', 'config.rb']

# configuration required for some pages

#domain: http://ioioj5.github.io
domain: http://www.woniu.me
author: __都非拉得
email: peng_du2007@qq.com

theme: jekyll-theme-hacker